name: BuildSite
on:
  pull_request:
    branches:
      - master
    paths:
      - src/content/**
      - src/templates/**
      - tools/generate/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Update timestamp for modified files
      run: |
        echo "files changed in commit $GITHUB_SHA:"
        git diff-tree --no-commit-id --name-only -r $GITHUB_SHA
        echo "Updating timestamp in any markdown chapter files"
        git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep "^src\/content\/[a-z]*\/[0-9]*\/[a-z0-9-]*.md" | xargs -r sed -i "s/^last_updated: [0-9-]*T/last_updated: $(date '+%Y-%m-%d')T/"
        git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | grep "^src\/templates\/[a-z]*/[0-9]*\/[a-z0-9-]*.html" | xargs -r sed -i "s/\"dateModified\": \"[0-9-]*T/\"dateModified\": \"$(date '+%Y-%m-%d')T/"
        echo "Updated timestamps:"
        git diff
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version:  12.x
    - name: Generate the chapters
      run: |
        echo "regenerating chapters"
        cd src
        npm install
        echo "regenerating chapters"
        npm run generate
    - name: Commit changes
      env:
        REPO_OWNER_EMAIL: ${{ github.repository.owner.email }}
      run: |
        echo "Checking git status"
        git status
        echo "Adding templates and content directory"
        git config --global user.email "${{ secrets.PUSH_EMAIL }}"
        git config --global user.name "Automatic Update"
        git add src/templates
        git add src/content
        echo "Commiting changes"
        git commit -m "Regenerated chapters"
        echo 'machine github.com login ${{ secrets.PUSH_USERNAME }} password ${{ secrets.PUSH_TOKEN }}' > ~/.netrc
        git push origin master
