name: Compress images
on:
  push:
    branches:
      - master
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    if: github.repository == 'bazzadp/almanac.httparchive.org'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: change file
      run: |
        sed 's/print.css?v=[0-9][0-9]*/print.css?v=23/' -i src/templates/base.html
    - name: calibreapp/image-actions
      id: calibre
      uses: bazzadp/image-actions@handle_forks_better
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        compressOnly: true

    - name: Create New Pull Request
      uses: peter-evans/create-pull-request@master
      with:
        title: Compressed Images
        branch-suffix: timestamp
        commit-message: Compressed Images
        body: ${{ steps.calibre.outputs.calibre_markdown }}
