name: Compress images
on:
  push:
    branches:
      - master
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    if: github.repository == 'bazzadp/almanac.httparchive.org'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: calibreapp/image-actions
      uses: bazzadp/image-actions@handle_forks_better
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
