#Runs "npm run generate" on any pushes to markdown, templates or generate scripts and adds a commit to this branch for changed files
#We do it on a push, rather than on pull request, as that's more complicated (https://github.com/actions/checkout/issues/124)
name: Generate Chapters on Push
on:
  push:
    paths:
      - src/content/**
      - src/templates/**
      - tools/generate/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version:  12.x
    - name: Generate the chapters
      run: |
        echo "regenerating chapters"
        cd src
        npm install
        echo "regenerating chapters"
        npm run generate
    - name: Commit changes
      run: |
        echo "Checking git status"
        git status
        echo "Adding templates and content directory"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "Automatic Update"
        git add src/templates
        echo "Commiting changes"
        git diff-index --quiet HEAD || git commit -m "Regenerated chapters"
        git push
