# Increments :
#   <link rel="stylesheet" href="/static/css/page.css?v=2
# to a unique number based on timestamp
name: Increment CSS Version
on:
  push:
    branches:
      - master
    paths:
      - static/css/**
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'bazzadp/almanac.httparchive.org'
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update CSS version for modified CSS files
      env:
        COMMIT_SHA: ${{ github.event.commits[0].id }}
      run: |
        echo "files changed in commit $COMMIT_SHA:"
        git diff-tree --no-commit-id --name-only -r $COMMIT_SHA
        echo "Incrementing any references to changed CSS files"
        git diff-tree --no-commit-id --name-only -r $COMMIT_SHA src/static/css | grep "\.css" | sed 's!.*/!!' | sed "s/\(.*\)/s\/\1?v=[0-9][0-9]*\/\1?v=$(date +%Y%m%d%H%M%S)\//" | sed -f - -i src/templates/base/*.html"
        git diff
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        title: Increment CSS version numbers
        branch-suffix: timestamp
        commit-message: Increment CSS version numbers
        body: |
            Increment CSS version numbers in case of breaking changes
            - Auto-generated by [create-pull-request][1] GitHub Action

            [1]: https://github.com/peter-evans/create-pull-request
        labels: development
        project: Web Almanac
        project-column: TODO
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
