name: Run Pytest
on:
  workflow_dispatch:
  push:
    paths:
      - src/*.py
      - src/requirements.txt
  pull_request:
    paths:
      - src/*.py
      - src/requirements.txt
jobs:
  pytest:
    # Skip duplicate job for local branches
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          cd src
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          cd src
          pytest
      - name: Run website
        run: |
          cd src
          python main.py background &
      - name: Run tests
        run: |
          cd src
          echo "Trying En Home page"
          if [ `curl -sL -w "%{http_code}" http://localhost:8080/en/2019/ -o /dev/null` != 200 ]; then false; fi
          echo "Trying Non-Existent page"
          if [ `curl -sL -w "%{http_code}" http://localhost:8080/en/201/ -o /dev/null` != 200 ]; then false; fi
          echo "Trying Home page"
          if [ `curl -sL -w "%{http_code}" http://localhost:8080 -o /dev/null` != 302 ]; then false; fi