name: UpdateDateAndBuildSite
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version:  12.x
    - name: Checkout the site
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Checkout and build the site
      run: |
        echo Running "npm run generate"
        cd src
        npm install
        npm run generate
        git status
