name: UpdateDateAndBuildSite
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version:  12.x
    - name: Checkout the site
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Checkout and build the site
      run: |
        echo Running "npm run generate"
        cd src
        npm install
        npm run generate
        git status
        git config --global user.email "barry_pollard@hotmail.com"
        git config --global user.name "Automatic Update"
        git commit -m "Regenerated chapters"
        echo 'machine github.com login ${{ secrets.PUSH_USERNAME }} password ${{ secrets.PUSH_TOKEN }}' > ~/.netrc
